name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt -r requirements-dev.txt
          pre-commit install

      - name: Lint (Black check)
        run: |
          black --check .

      - name: Pre-commit (selected hooks)
        run: |
          pre-commit run --all-files

      - name: Smoke tests
        run: |
          python - <<'PY'
          from app.database import Base, engine
          Base.metadata.create_all(bind=engine)
          import app.main as m
          assert m.app.title == 'Pastel Time Tracker'
          print('App import OK')
          PY

